### ISSUE TITLE
Expander error in flonum-bits.rkt

### ISSUE THREAD

**Issue by sabauma** [samth/pycket#168]
This problem may be related to the issues we were having with the expander.
I get the following stack trace when attempting to expand the file

    <racket root>/share/racket/pkgs/math-lib/math/private/flonum/flonum-bits.rkt

```
Traceback (most recent call last):
  File "/home/spenser/src/pycket/pycket/__main__.py", line 32, in main
    sys.exit(f(sys.argv))
  File "/home/spenser/src/pycket/pycket/entry_point.py", line 17, in entry_point
    return actual_entry(argv)
  File "/home/spenser/src/pycket/pycket/entry_point.py", line 37, in actual_entry
    ast = load_json_ast_rpython(json_ast, modtable)
  File "/home/spenser/src/pycket/pycket/expand.py", line 234, in load_json_ast_rpython
    return _to_module(pycket_json.loads(data), modtable).assign_convert_module()
  File "/home/spenser/src/pycket/pycket/expand.py", line 319, in _to_module
    body = [_to_ast(x, modtable) for x in v["body-forms"].value_array()]
  File "/home/spenser/src/pycket/pycket/expand.py", line 513, in _to_ast
    body = _to_ast(obj["define-values-body"], modtable)
  File "/home/spenser/src/pycket/pycket/expand.py", line 446, in _to_ast
    return Begin([_to_ast(x, modtable) for x in arr[1:]])
  File "/home/spenser/src/pycket/pycket/expand.py", line 484, in _to_ast
    assert 0, "Unexpected ast-element element: %s" % json.tostring()
AssertionError: Unexpected ast-element element: [{"source-name": "quote-syntax"}, [{"source-name": ":-internal", "source-module": ["/home/spenser/bin/racket/share/racket/pkgs/typed-racket-lib/typed-racket/typecheck/internal-forms.rkt", "forms"]}, {"source-name": "flonum->bit-field", "source-module": ["/home/spenser/bin/racket/share/racket/pkgs/math-lib/math/private/flonum/flonum-bits.rkt"]}, [{"source-name": "Flonum", "source-module": ["/home/spenser/bin/racket/share/racket/pkgs/typed-racket-lib/typed-racket/base-env/base-types.rkt"]}, {"source-name": "->", "source-module": ["/home/spenser/bin/racket/share/racket/pkgs/typed-racket-lib/typed-racket/base-env/base-types-extra.rkt"]}, {"source-name": "Natural", "source-module": ["/home/spenser/bin/racket/share/racket/pkgs/typed-racket-lib/typed-racket/base-env/base-types.rkt"]}]], {"keyword": "local"}]
> /home/spenser/src/pycket/pycket/expand.py(484)_to_ast()
-> assert 0, "Unexpected ast-element element: %s" % json.tostring()
```

The JSON for being generated for the `quote-syntax` form is not what the
parser is expecting, rather it looks like `quote-syntax` forms are being turned
into applications.

**Comment by samth** [comment]
I get this error on a bunch of the tests on my machine, but it doesn't happen on Travis.

**Comment by sabauma** [comment]
That's odd. I do not observe this problem on my machine when running the test suite.

**Comment by sabauma** [comment]
It looks like this problem is infecting more programs. It may have taken a while to notice due to stale JSON files, but I am unable to run many of the gradual typing variations. The code below is a smaller example extracted from the GT benchmarks.

```racket
#lang typed/racket/base

;; Simple streams library.
;; For building and using infinite lists.

(provide (struct-out stream) make-stream)

;; ;; A stream is a cons of a value and a thunk that computes the next value when applied
(struct: stream ([first : Natural] [rest : (-> stream)]))

;;--------------------------------------------------------------------------------------------------

(: make-stream (-> Natural (-> stream) stream))
(define (make-stream hd thunk)
  (stream hd thunk))
```

**Comment by samth** [comment]
This problem went away, right?

**Comment by sabauma** [comment]
Yes.
