### ISSUE TITLE
Properly handle auto values in non-immediate super types

### ISSUE THREAD

**Issue by sabauma** [samth/pycket#179]
Consider the struct definition

```racket
#lang racket/base

(struct test1 ([a #:auto ] [b #:auto] [c #:auto]) #:auto-value 0)
(struct test2 test1 ())
(struct test3 test2 ())

(test1)
(test2)
(test3)
(procedure-arity test3) ;; => 0 in Racket, 3 in Pycket
```

The struct types `test2` and `test3` inherit the 3 auto fields from `test1`.  Pycket is able to properly instantiate `test1` and `test2` objects, but fails on `(test3)` with the error message:

```
ERROR:
test3: arity mismatch
  while executing: (call-with-values (lambda () (test33 )) print-values)
  in module: test
Traceback (most recent call last):
  File "/home/spenser/src/pycket/pycket/__main__.py", line 32, in main
    sys.exit(f(sys.argv))
  File "/home/spenser/src/pycket/pycket/entry_point.py", line 23, in entry_point
    return actual_entry(argv)
  File "/home/spenser/src/pycket/pycket/entry_point.py", line 57, in actual_entry
    val = interpret_module(ast, env)
  File "/home/spenser/src/pycket/pycket/interpreter.py", line 2029, in interpret_module
    m.interpret_mod(env)
  File "/home/spenser/src/pycket/pycket/interpreter.py", line 478, in interpret_mod
    return self._interpret_mod(env)
  File "/home/spenser/src/pycket/pycket/interpreter.py", line 534, in _interpret_mod
    vs = interpret_one(f, self.env)
  File "/home/spenser/src/pycket/pycket/interpreter.py", line 2006, in interpret_one
    inner_interpret(ast, env, cont)
  File "/home/spenser/src/pycket/pycket/interpreter.py", line 1974, in inner_interpret_two_state
    ast, env, cont = ast.interpret(env, cont)
  File "/home/spenser/src/pycket/pycket/cont.py", line 243, in interpret
    return func(*args)
  File "/home/spenser/src/pycket/pycket/interpreter.py", line 596, in safe_return_multi_vals
    return cont.plug_reduce(vals, env)
  File "/home/spenser/src/pycket/pycket/cont.py", line 187, in plug_reduce
    return func(*args)
  File "/home/spenser/src/pycket/pycket/values_struct.py", line 850, in constr_proc_cont
    raise SchemeException("%s: arity mismatch" % self.constr_name)
SchemeException: test3: arity mismatch
> /home/spenser/src/pycket/pycket/values_struct.py(850)constr_proc_cont()
-> raise SchemeException("%s: arity mismatch" % self.constr_name)
```

At least 2 GT benchmarks are getting hit by this bug.

**Comment by sabauma** [comment]
Fixed by 07bef841bdcce0bce0fb379dab02e4cc66d8c160 and subsequent fixups
