### ISSUE TITLE
Unable to run MBTA on certain GT configurations

### ISSUE THREAD

**Issue by sabauma** [samth/pycket#194]
When trying to run configuration1000 under Pycket, I get the error shown below.
This was generated with a fresh Racket install, so I don't think the problem is
stale JSON files.

```
14:21:37 $ pypy ~/src/pycket/targetpycket.py main.rkt
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-default-9/platcheck_4.c -o /tmp/usession-default-9/platcheck_4.o
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-default-9/platcheck_6.c -o /tmp/usession-default-9/platcheck_6.o
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-default-9/platcheck_11.c -o /tmp/usession-default-9/platcheck_11.o
[platform:execute] gcc /tmp/usession-default-9/platcheck_11.o -pthread -Wl,--export-dynamic -lintl -lrt -o /tmp/usession-default-9/platcheck_11
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused -fPIC -fvisibility=hidden -g -O0 -DRPY_EXTERN=RPY_EXPORTED -DRPYTHON_LL2CTYPES -I/home/spenser/src/pycket/pypy/rpython/translator/c /home/spenser/src/pycket/pypy/rpython/translator/c/src/thread.c -o /tmp/usession-default-9/rpython/translator/c/src/thread.o
[platform:execute] gcc -shared /tmp/usession-default-9/rpython/translator/c/src/thread.o -pthread -Wl,--export-dynamic -lrt -o /tmp/usession-default-9/shared_cache/externmod.so
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused -fPIC -fvisibility=hidden -g -O0 -DRPY_EXTERN=RPY_EXPORTED -DRPYTHON_LL2CTYPES /tmp/usession-default-9/module_cache/module_0.c -o /tmp/usession-default-9/module_cache/module_0.o
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused -fPIC -fvisibility=hidden -g -O0 -DRPY_EXTERN=RPY_EXPORTED -DRPYTHON_LL2CTYPES /tmp/usession-default-9/module_cache/module_1.c -o /tmp/usession-default-9/module_cache/module_1.o
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused -fPIC -fvisibility=hidden -g -O0 -DRPY_EXTERN=RPY_EXPORTED -DRPYTHON_LL2CTYPES /tmp/usession-default-9/module_cache/module_2.c -o /tmp/usession-default-9/module_cache/module_2.o
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused -fPIC -fvisibility=hidden -g -O0 -DRPY_EXTERN=RPY_EXPORTED -DRPYTHON_LL2CTYPES /tmp/usession-default-9/module_cache/module_3.c -o /tmp/usession-default-9/module_cache/module_3.o
[platform:execute] gcc -shared /tmp/usession-default-9/module_cache/module_0.o /tmp/usession-default-9/module_cache/module_1.o /tmp/usession-default-9/module_cache/module_2.o /tmp/usession-default-9/module_cache/module_3.o -pthread -Wl,--export-dynamic -lrt -o /tmp/usession-default-9/shared_cache/externmod_0.so
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused -fPIC -fvisibility=hidden -g -O0 -DRPY_EXTERN=RPY_EXPORTED -DRPYTHON_LL2CTYPES /tmp/usession-default-9/module_cache/module_4.c -o /tmp/usession-default-9/module_cache/module_4.o
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused -fPIC -fvisibility=hidden -g -O0 -DRPY_EXTERN=RPY_EXPORTED -DRPYTHON_LL2CTYPES /tmp/usession-default-9/module_cache/module_5.c -o /tmp/usession-default-9/module_cache/module_5.o
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused -fPIC -fvisibility=hidden -g -O0 -DRPY_EXTERN=RPY_EXPORTED -DRPYTHON_LL2CTYPES /tmp/usession-default-9/module_cache/module_6.c -o /tmp/usession-default-9/module_cache/module_6.o
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused -fPIC -fvisibility=hidden -g -O0 -DRPY_EXTERN=RPY_EXPORTED -DRPYTHON_LL2CTYPES /tmp/usession-default-9/module_cache/module_7.c -o /tmp/usession-default-9/module_cache/module_7.o
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused -fPIC -fvisibility=hidden -g -O0 -DRPY_EXTERN=RPY_EXPORTED -DRPYTHON_LL2CTYPES /tmp/usession-default-9/module_cache/module_8.c -o /tmp/usession-default-9/module_cache/module_8.o
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused -fPIC -fvisibility=hidden -g -O0 -DRPY_EXTERN=RPY_EXPORTED -DRPYTHON_LL2CTYPES /tmp/usession-default-9/module_cache/module_9.c -o /tmp/usession-default-9/module_cache/module_9.o
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused -fPIC -fvisibility=hidden -g -O0 -DRPY_EXTERN=RPY_EXPORTED -DRPYTHON_LL2CTYPES /tmp/usession-default-9/module_cache/module_10.c -o /tmp/usession-default-9/module_cache/module_10.o
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused -fPIC -fvisibility=hidden -g -O0 -DRPY_EXTERN=RPY_EXPORTED -DRPYTHON_LL2CTYPES /tmp/usession-default-9/module_cache/module_11.c -o /tmp/usession-default-9/module_cache/module_11.o
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused -fPIC -fvisibility=hidden -g -O0 -DRPY_EXTERN=RPY_EXPORTED -DRPYTHON_LL2CTYPES /tmp/usession-default-9/module_cache/module_12.c -o /tmp/usession-default-9/module_cache/module_12.o
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused -fPIC -fvisibility=hidden -g -O0 -DRPY_EXTERN=RPY_EXPORTED -DRPYTHON_LL2CTYPES /tmp/usession-default-9/module_cache/module_13.c -o /tmp/usession-default-9/module_cache/module_13.o
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused -fPIC -fvisibility=hidden -g -O0 -DRPY_EXTERN=RPY_EXPORTED -DRPYTHON_LL2CTYPES /tmp/usession-default-9/module_cache/module_14.c -o /tmp/usession-default-9/module_cache/module_14.o
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused -fPIC -fvisibility=hidden -g -O0 -DRPY_EXTERN=RPY_EXPORTED -DRPYTHON_LL2CTYPES /tmp/usession-default-9/module_cache/module_15.c -o /tmp/usession-default-9/module_cache/module_15.o
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused -fPIC -fvisibility=hidden -g -O0 -DRPY_EXTERN=RPY_EXPORTED -DRPYTHON_LL2CTYPES /tmp/usession-default-9/module_cache/module_16.c -o /tmp/usession-default-9/module_cache/module_16.o
[platform:execute] gcc -shared /tmp/usession-default-9/module_cache/module_4.o /tmp/usession-default-9/module_cache/module_5.o /tmp/usession-default-9/module_cache/module_6.o /tmp/usession-default-9/module_cache/module_7.o /tmp/usession-default-9/module_cache/module_8.o /tmp/usession-default-9/module_cache/module_9.o /tmp/usession-default-9/module_cache/module_10.o /tmp/usession-default-9/module_cache/module_11.o /tmp/usession-default-9/module_cache/module_12.o /tmp/usession-default-9/module_cache/module_13.o /tmp/usession-default-9/module_cache/module_14.o /tmp/usession-default-9/module_cache/module_15.o /tmp/usession-default-9/module_cache/module_16.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-default-9/shared_cache/externmod_1.so
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused -fPIC -fvisibility=hidden -g -O0 -DRPY_EXTERN=RPY_EXPORTED -DRPYTHON_LL2CTYPES /tmp/usession-default-9/module_cache/module_17.c -o /tmp/usession-default-9/module_cache/module_17.o
[platform:execute] gcc -shared /tmp/usession-default-9/module_cache/module_17.o -pthread -Wl,--export-dynamic -lrt -o /tmp/usession-default-9/shared_cache/externmod_2.so
Traceback (most recent call last):
  File "/home/spenser/src/pycket/pycket/__main__.py", line 32, in main
    sys.exit(f(sys.argv))
  File "/home/spenser/src/pycket/pycket/entry_point.py", line 22, in entry_point
    return actual_entry(argv)
  File "/home/spenser/src/pycket/pycket/entry_point.py", line 55, in actual_entry
    val = interpret_module(ast, env)
  File "/home/spenser/src/pycket/pycket/interpreter.py", line 2081, in interpret_module
    m.interpret_mod(env)
  File "/home/spenser/src/pycket/pycket/interpreter.py", line 519, in interpret_mod
    return self._interpret_mod(env)
  File "/home/spenser/src/pycket/pycket/interpreter.py", line 561, in _interpret_mod
    interpret_one(r, self.env)
  File "/home/spenser/src/pycket/pycket/interpreter.py", line 2058, in interpret_one
    inner_interpret(ast, env, cont)
  File "/home/spenser/src/pycket/pycket/interpreter.py", line 2026, in inner_interpret_two_state
    ast, env, cont = ast.interpret(env, cont)
  File "/home/spenser/src/pycket/pycket/AST.py", line 25, in interpret
    return return_value_direct(self.interpret_simple(env), env, cont)
  File "/home/spenser/src/pycket/pycket/interpreter.py", line 608, in interpret_simple
    module.interpret_mod(top)
  File "/home/spenser/src/pycket/pycket/interpreter.py", line 519, in interpret_mod
    return self._interpret_mod(env)
  File "/home/spenser/src/pycket/pycket/interpreter.py", line 556, in _interpret_mod
    interpret_one(self.lang, self.env)
  File "/home/spenser/src/pycket/pycket/interpreter.py", line 2058, in interpret_one
    inner_interpret(ast, env, cont)
  File "/home/spenser/src/pycket/pycket/interpreter.py", line 2026, in inner_interpret_two_state
    ast, env, cont = ast.interpret(env, cont)
  File "/home/spenser/src/pycket/pycket/AST.py", line 25, in interpret
    return return_value_direct(self.interpret_simple(env), env, cont)
  File "/home/spenser/src/pycket/pycket/interpreter.py", line 605, in interpret_simple
    module = self.find_module(env)
  File "/home/spenser/src/pycket/pycket/interpreter.py", line 596, in find_module
    module = self.loader.lazy_load(self.fname)
  File "/home/spenser/src/pycket/pycket/expand.py", line 484, in lazy_load
    return self.expand_file_cached(fname)
  File "/home/spenser/src/pycket/pycket/expand.py", line 449, in expand_file_cached
    json_file = ensure_json_ast_run(rkt_file, self._lib_string())
  File "/home/spenser/src/pycket/pycket/expand.py", line 229, in ensure_json_ast_run
    return expand_file_to_json(file_name, json, lib)
  File "/home/spenser/src/pycket/pycket/expand.py", line 143, in expand_file_to_json
    return wrap_for_tempfile(_expand_file_to_json)(rkt_file, json_file, lib)
  File "/home/spenser/src/pycket/pycket/expand.py", line 133, in wrap
    out = func(rkt_file, tmp_json_file, lib) # this may be a problem in the future if the given func doesn't expect a third arg (lib)
  File "/home/spenser/src/pycket/pycket/expand.py", line 153, in _expand_file_to_json
    raise ValueError("Cannot access file %s" % rkt_file)
ValueError: Cannot access file /home/spenser/bin/racket/collects/racket/base.rkt
> /home/spenser/src/pycket/pycket/expand.py(153)_expand_file_to_json()
-> raise ValueError("Cannot access file %s" % rkt_file)
(Pdb) p rkt_file
'/home/spenser/bin/racket/collects/racket/base.rkt'
(Pdb)
```

**Comment by samth** [comment]
This turns out to be fake.
