### ISSUE TITLE
More chaperone/keyword badness

### ISSUE THREAD

**Issue by samth** [samth/pycket#195]
```racket
#lang racket/base
(define v (lambda (#:x (x #f)) #f))
(define cv2 (chaperone-procedure v (lambda (#:x (x #f)) (list '#f))))
(cv2 #:x #f)
```

**Comment by samth** [comment]
Here's the key error message:

```
ERROR:
expected root-struct as argument 0 to <struct-field-accessor-method>, got #<procedure>
  while executing: (let ([AppRator_2 (checked-procedure-check-and-extract struct:keyword-procedure cv2 keyword-procedure-extract '('#:x) 2)][AppRand1_2 (list #f)]) (let ([AppRand0_1 (AppRator_2 '('#:x) AppRand1_2)]) (display AppRand0_1)))
  in module: test4
Traceback (most recent call last):
  File "/home/samth/sw/pycket/pycket/__main__.py", line 32, in main
    sys.exit(f(sys.argv))
  File "/home/samth/sw/pycket/pycket/entry_point.py", line 23, in entry_point
    return actual_entry(argv)
  File "/home/samth/sw/pycket/pycket/entry_point.py", line 56, in actual_entry
    val = interpret_module(ast, env)
  File "/home/samth/sw/pycket/pycket/interpreter.py", line 2080, in interpret_module
    m.interpret_mod(env)
  File "/home/samth/sw/pycket/pycket/interpreter.py", line 518, in interpret_mod
    return self._interpret_mod(env)
  File "/home/samth/sw/pycket/pycket/interpreter.py", line 573, in _interpret_mod
    vs = interpret_one(f, self.env)
  File "/home/samth/sw/pycket/pycket/interpreter.py", line 2057, in interpret_one
    inner_interpret(ast, env, cont)
  File "/home/samth/sw/pycket/pycket/interpreter.py", line 2025, in inner_interpret_two_state
    ast, env, cont = ast.interpret(env, cont)
  File "/home/samth/sw/pycket/pycket/interpreter.py", line 862, in interpret
    return w_callable.call_with_extra_info(args_w, env, cont, self)
  File "/home/samth/sw/pycket/pycket/prims/expose.py", line 192, in func_arg_unwrap
    raise SchemeException(type_errormsg + arg.tostring())
SchemeException: expected root-struct as argument 0 to <struct-field-accessor-method>, got #<procedure>
```

**Comment by samth** [comment]
The core problem seems to be that `W_StructFieldAccessor` is unhappy about being called with the result of `chaperone-procedure`.
